// ── Lycées (10) ──────────────────────────────────────────
const LYCEES = [
  {
    id: "lpzk",
    nom: "Lycée National Philippe Zinda Kaboré",
    sigle: "LPZK",
    logo: "https://lefaso.net/IMG/logo/siteon101.png",
    image: "",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Koulouba",
    description: "Lycée historique du Burkina Faso.",
    descriptionDetaillee: "Un établissement mythique qui a formé de grands cadres burkinabè.",
    prixMin: 12000,
    prixMax: 20000,
    prixLabel: "12 000 – 20 000 FCFA/an",
    series: ["Série A", "Série C", "Série D"],
    notationSystem: "National",
    telephone: "+226 25 30 63 00"
  },
  {
    id: "lse",
    nom: "Lycée Français Saint-Exupéry",
    sigle: "LSE",
    logo: "https://lfse.org/IMG/logo/siteon1.png",
    image: "https://lfse.org/IMG/jpg/vue_aerienne.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Wemtenga",
    description: "Établissement à programme français.",
    descriptionDetaillee: "Excellence académique et environnement multiculturel sous tutelle de l'AEFE.",
    prixMin: 1500000,
    prixMax: 3000000,
    prixLabel: "Env. 2 000 000 FCFA/an",
    series: ["Bac Français (S, ES, L)"],
    notationSystem: "Français",
    telephone: "+226 25 31 10 00",
    site: "https://lfse.org"
  },
  {
    id: "lmn",
    nom: "Lycée Marien Ngouabi",
    sigle: "LMN",
    logo: "https://lefaso.net/IMG/logo/lmn_logo.png",
    image: "https://lefaso.net/IMG/jpg/marien_ngouabi.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Baskuy",
    description: "Lycée public renommé pour ses résultats.",
    descriptionDetaillee: "Situé au centre-ville, il accueille une forte population scolaire vers la réussite au Bac.",
    prixMin: 12000,
    prixMax: 25000,
    prixLabel: "12 000 – 25 000 FCFA/an",
    series: ["Série A", "Série C", "Série D"],
    notationSystem: "National",
    telephone: "+226 25 35 11 11"
  },
  {
    id: "lmo",
    nom: "Lycée Municipal de Ouagadougou",
    sigle: "LMO",
    logo: "https://lefaso.net/IMG/logo/lmo_logo.png",
    image: "https://lefaso.net/IMG/jpg/lmo_pissy.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Pissy",
    description: "Établissement municipal de proximité.",
    descriptionDetaillee: "Offre un enseignement public de qualité aux habitants des quartiers Ouest.",
    prixMin: 10000,
    prixMax: 15000,
    prixLabel: "10 000 – 15 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National",
    telephone: "+226 25 34 00 00"
  },
  {
    id: "lpk",
    nom: "Lycée Privé Karkandé",
    sigle: "LPK",
    logo: "https://iafrican.bf/logo_lpk.png",
    image: "https://iafrican.bf/lpk_photo.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Karpala",
    description: "Lycée privé d'excellence à Karpala.",
    descriptionDetaillee: "Cadre d'études discipliné et innovant pour les élèves des séries scientifiques.",
    prixMin: 150000,
    prixMax: 400000,
    prixLabel: "150 000 – 400 000 FCFA/an",
    series: ["Série C", "Série D", "Série A"],
    notationSystem: "National",
    telephone: "+226 25 40 40 40"
  },
  {
    id: "lbg",
    nom: "Lycée Bogodogo",
    sigle: "LBO",
    logo: "https://lefaso.net/logo_lbo.png",
    image: "https://lefaso.net/lbo_campus.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Dassasgo",
    description: "L'un des plus grands lycées de l'Est de la capitale.",
    descriptionDetaillee: "Réputé pour son dynamisme et le sérieux de son corps enseignant.",
    prixMin: 12000,
    prixMax: 20000,
    prixLabel: "12 000 – 20 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National"
  },
  {
    id: "lsc",
    nom: "Lycée Saint-Charles",
    sigle: "LSC",
    logo: "https://stcharles.bf/logo.png",
    image: "https://stcharles.bf/batiment.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Somgandé",
    description: "Établissement confessionnel catholique.",
    descriptionDetaillee: "Discipline de fer et éducation spirituelle pour des résultats records au Bac.",
    prixMin: 200000,
    prixMax: 500000,
    prixLabel: "200 000 – 500 000 FCFA/an",
    series: ["Série A", "Série D", "Série C"],
    notationSystem: "National",
    telephone: "+226 25 35 22 22"
  },
  {
    id: "lwp",
    nom: "Lycée Wend Panga",
    sigle: "LWP",
    logo: "https://wendpanga.bf/logo.png",
    image: "https://wendpanga.bf/lycee.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Secteur 15",
    description: "Établissement privé tourné vers la réussite.",
    descriptionDetaillee: "Un cadre familial et des classes à effectifs réduits.",
    prixMin: 180000,
    prixMax: 450000,
    prixLabel: "180 000 – 450 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National"
  },
  {
    id: "lmp",
    nom: "Lycée Mixte de Pissy",
    sigle: "LMP",
    logo: "https://pissy.bf/logo.png",
    image: "https://pissy.bf/photo.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Pissy",
    description: "Grand lycée public populaire.",
    descriptionDetaillee: "Dessert toute la zone Ouest de Ouagadougou avec des résultats constants.",
    prixMin: 12000,
    prixMax: 22000,
    prixLabel: "12 000 – 22 000 FCFA/an",
    series: ["Série A", "Série D", "Série C"],
    notationSystem: "National"
  },
  {
    id: "lsn",
    nom: "Lycée de Sig-Nonghin",
    sigle: "LSN",
    logo: "https://signonghin.bf/logo.png",
    image: "https://signonghin.bf/campus.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Sig-Nonghin",
    description: "Établissement public de référence au Nord.",
    descriptionDetaillee: "Un corps enseignant expérimenté pour encadrer les élèves du Nord de la ville.",
    prixMin: 11000,
    prixMax: 20000,
    prixLabel: "11 000 – 20 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National"
  }
];