// ── CURSUS BF — data.js ─────────────────────────────────────
// Base de données complète (30 établissements)
// =========================================================

// ── Universités (10) ──────────────────────────────────────
const UNIVERSITES = [
  {
    id: "ujk",
    nom: "Université Joseph Ki-Zerbo",
    sigle: "UJKZ",
    logo: "https://upload.wikimedia.org/wikipedia/fr/b/bd/Logo_Université_Joseph_Ki-Zerbo.png",
    image: "https://lefaso.net/IMG/jpg/ujkz_batiment.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Zogona",
    description: "Le plus grand établissement d'enseignement supérieur public du Burkina Faso.",
    descriptionDetaillee: "Fondée en 1974, l'UJKZ est le pilier de l'enseignement supérieur. Elle regroupe plusieurs UFR (Sciences, Lettres, Santé, etc.) et accueille des dizaines de milliers d'étudiants.",
    prixMin: 15000,
    prixMax: 50000,
    prixLabel: "15 000 – 50 000 FCFA/an",
    filieres: ["Médecine", "Droit", "Sciences Économiques", "Lettres Modernes", "Mathématiques", "Physique", "SVT", "Sociologie"],
    notationSystem: "LMD",
    telephone: "+226 25 30 70 64",
    site: "https://ujkz.bf",
    fondee: 1974
  },
  {
    id: "uts",
    nom: "Université Thomas Sankara",
    sigle: "UTS",
    logo: "https://www.uts.bf/images/logo-footer.png",
    image: "https://lefaso.net/IMG/jpg/uts_campus.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Gonsé",
    description: "Université spécialisée en sciences juridiques, politiques et de gestion.",
    descriptionDetaillee: "Anciennement Ouaga II, l'UTS est située sur un campus moderne et spacieux. Elle est reconnue pour sa filière économie et gestion d'excellence.",
    prixMin: 15000,
    prixMax: 50000,
    prixLabel: "15 000 – 50 000 FCFA/an",
    filieres: ["Sciences Juridiques", "Économie", "Gestion", "Sciences Politiques", "Informatique"],
    notationSystem: "LMD",
    telephone: "+226 25 36 06 00",
    site: "https://www.uts.bf",
    fondee: 2014
  },
  {
    id: "auben",
    nom: "Université Aube Nouvelle",
    sigle: "U-AUBEN",
    logo: "https://brandfetch.com/_next/image?url=https%3A%2F%2Fasset.brandfetch.io%2Fidr-9A8_uX%2FidS8P8f8f8.png&w=640&q=75",
    image: "https://legrandfrere.africa/wp-content/uploads/2021/04/Universite-Aube-Nouvelle-U-Auben-Campus-1200-Logements.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "1200 Logements",
    description: "Établissement privé de référence au Burkina Faso.",
    descriptionDetaillee: "U-Aube Nouvelle offre un cadre d'apprentissage moderne avec des diplômes reconnus internationalement par le CAMES.",
    prixMin: 400000,
    prixMax: 1200000,
    prixLabel: "400 000 – 1 200 000 FCFA/an",
    filieres: ["Finance-Comptabilité", "Marketing", "Réseaux & Télécoms", "Génie Civil", "Droit des Affaires"],
    notationSystem: "LMD",
    telephone: "+226 25 37 44 44",
    site: "https://www.u-auben.com",
    fondee: 1992
  },
  {
    id: "iam",
    nom: "Université de l'Unité Africaine (IAM)",
    sigle: "UUA",
    logo: "https://iamburkina.com/wp-content/uploads/2020/12/logo-uua-iam.png",
    image: "https://lefaso.net/IMG/jpg/iam_zad.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "ZAD",
    description: "École leader en management et gestion.",
    descriptionDetaillee: "L'UUA/IAM forme les futurs cadres et leaders africains dans un environnement moderne.",
    prixMin: 500000,
    prixMax: 1500000,
    prixLabel: "500 000 – 1 500 000 FCFA/an",
    filieres: ["Management", "Audit & Contrôle", "Transport-Logistique", "Communication", "Relation Internationales"],
    notationSystem: "LMD",
    telephone: "+226 25 37 56 56",
    site: "https://iamburkina.com"
  },
  {
    id: "ispp",
    nom: "Institut Supérieur Privé Polytechnique",
    sigle: "ISPP",
    logo: "https://ispp-edu.com/wp-content/uploads/2019/12/ispp-logo.png",
    image: "https://lefaso.net/IMG/jpg/ispp_campus.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Kouritenga",
    description: "Établissement technique et polytechnique privé.",
    descriptionDetaillee: "Un large éventail de formations professionnelles reconnues, avec plusieurs sites à Ouagadougou.",
    prixMin: 350000,
    prixMax: 900000,
    prixLabel: "350 000 – 900 000 FCFA/an",
    filieres: ["Banque & Microfinance", "Assurance", "Génie Mines", "Transit", "Journalisme"],
    notationSystem: "LMD",
    telephone: "+226 25 36 78 00",
    site: "https://ispp-edu.com"
  },
  {
    id: "est",
    nom: "École Supérieure de Technologie",
    sigle: "ESTA",
    logo: "https://lefaso.net/IMG/logo/esta_logo.png",
    image: "https://esta.bf/templates/yootheme/cache/esta_batiment.webp",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Larlé",
    description: "Formation de pointe en technologies de l'information.",
    descriptionDetaillee: "ESTA est réputée pour ses ingénieurs en informatique et réseaux, formés aux dernières technologies.",
    prixMin: 450000,
    prixMax: 950000,
    prixLabel: "450 000 – 950 000 FCFA/an",
    filieres: ["Génie Logiciel", "Systèmes & Réseaux", "Maintenance", "Électronique", "Télécoms"],
    notationSystem: "LMD",
    telephone: "+226 25 31 82 82",
    site: "https://esta.bf"
  },
  {
    id: "ulb",
    nom: "Université Libre du Burkina",
    sigle: "ULB",
    logo: "http://www.ulb.bf/images/logo.png",
    image: "https://lefaso.net/IMG/jpg/ulb_campus.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Somgandé",
    description: "L'une des premières universités privées du Burkina.",
    descriptionDetaillee: "L'ULB offre une large gamme de formations en sciences sociales, droit et économie dans un cadre calme.",
    prixMin: 300000,
    prixMax: 800000,
    prixLabel: "300 000 – 800 000 FCFA/an",
    filieres: ["Droit", "Comptabilité", "Sociologie", "Gestion des RH", "Marketing"],
    notationSystem: "LMD",
    telephone: "+226 25 35 60 70",
    site: "http://www.ulb.bf"
  },
  {
    id: "hetec",
    nom: "HETEC Burkina",
    sigle: "HETEC",
    logo: "https://groupehetec.net/images/logo_hetec.png",
    image: "https://lefaso.net/IMG/jpg/hetec_ouaga.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Tampouy",
    description: "Haute École de Technologie et de Commerce.",
    descriptionDetaillee: "HETEC est implantée dans plusieurs pays et offre des certifications internationales en management.",
    prixMin: 400000,
    prixMax: 1100000,
    prixLabel: "400 000 – 1 100 000 FCFA/an",
    filieres: ["Marketing Digital", "Audit", "Logistique", "Finance", "Communication"],
    notationSystem: "LMD",
    telephone: "+226 25 41 09 10",
    site: "https://hetecburkina.com"
  },
  {
    id: "utm",
    nom: "Université de Technologie et de Management",
    sigle: "UTM",
    logo: "http://www.utmbf.com/logo.png",
    image: "https://lefaso.net/IMG/jpg/utm_faso.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Gounghin",
    description: "Modernité et innovation au service de la formation.",
    descriptionDetaillee: "L'UTM se distingue par ses programmes centrés sur l'innovation technologique et le management moderne.",
    prixMin: 450000,
    prixMax: 1000000,
    prixLabel: "450 000 – 1 000 000 FCFA/an",
    filieres: ["Management de Projet", "Systèmes d'Information", "E-Business", "RH", "Banque"],
    notationSystem: "LMD",
    telephone: "+226 25 34 50 50",
    site: "http://www.utmbf.com"
  },
  {
    id: "unz",
    nom: "Université Norbert Zongo",
    sigle: "UNZ",
    logo: "https://unz.bf/wp-content/uploads/2021/04/logo_unz.png",
    image: "https://lefaso.net/IMG/jpg/unz_koudougou.jpg",
    type: "public",
    localite: "Koudougou",
    quartier: "Centre",
    description: "Le pôle d'excellence en sciences de l'éducation.",
    descriptionDetaillee: "Située à Koudougou, l'UNZ forme les enseignants du pays et offre des cursus en sciences et lettres.",
    prixMin: 15000,
    prixMax: 50000,
    prixLabel: "15 000 – 50 000 FCFA/an",
    filieres: ["Lettres", "Sciences", "Économie", "SVT", "Éducation"],
    notationSystem: "LMD",
    telephone: "+226 26 44 23 08",
    site: "https://unz.bf"
  }
];

// ── Lycées (10) ──────────────────────────────────────────
const LYCEES = [
  {
    id: "lpzk",
    nom: "Lycée National Philippe Zinda Kaboré",
    sigle: "LPZK",
    logo: "https://lefaso.net/IMG/logo/siteon101.png",
    image: "https://lefaso.net/IMG/jpg/zinda_historique.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Koulouba",
    description: "Lycée historique du Burkina Faso.",
    descriptionDetaillee: "Un établissement mythique qui a formé de grands cadres burkinabè.",
    prixMin: 12000,
    prixMax: 20000,
    prixLabel: "12 000 – 20 000 FCFA/an",
    series: ["Série A", "Série C", "Série D"],
    notationSystem: "National",
    telephone: "+226 25 30 63 00"
  },
  {
    id: "lse",
    nom: "Lycée Français Saint-Exupéry",
    sigle: "LSE",
    logo: "https://lfse.org/IMG/logo/siteon1.png",
    image: "https://lfse.org/IMG/jpg/vue_aerienne.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Wemtenga",
    description: "Établissement à programme français.",
    descriptionDetaillee: "Excellence académique et environnement multiculturel sous tutelle de l'AEFE.",
    prixMin: 1500000,
    prixMax: 3000000,
    prixLabel: "Env. 2 000 000 FCFA/an",
    series: ["Bac Français (S, ES, L)"],
    notationSystem: "Français",
    telephone: "+226 25 31 10 00",
    site: "https://lfse.org"
  },
  {
    id: "lmn",
    nom: "Lycée Marien Ngouabi",
    sigle: "LMN",
    logo: "https://lefaso.net/IMG/logo/lmn_logo.png",
    image: "https://lefaso.net/IMG/jpg/marien_ngouabi.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Baskuy",
    description: "Lycée public renommé pour ses résultats.",
    descriptionDetaillee: "Situé au centre-ville, il accueille une forte population scolaire vers la réussite au Bac.",
    prixMin: 12000,
    prixMax: 25000,
    prixLabel: "12 000 – 25 000 FCFA/an",
    series: ["Série A", "Série C", "Série D"],
    notationSystem: "National",
    telephone: "+226 25 35 11 11"
  },
  {
    id: "lmo",
    nom: "Lycée Municipal de Ouagadougou",
    sigle: "LMO",
    logo: "https://lefaso.net/IMG/logo/lmo_logo.png",
    image: "https://lefaso.net/IMG/jpg/lmo_pissy.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Pissy",
    description: "Établissement municipal de proximité.",
    descriptionDetaillee: "Offre un enseignement public de qualité aux habitants des quartiers Ouest.",
    prixMin: 10000,
    prixMax: 15000,
    prixLabel: "10 000 – 15 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National",
    telephone: "+226 25 34 00 00"
  },
  {
    id: "lpk",
    nom: "Lycée Privé Karkandé",
    sigle: "LPK",
    logo: "https://iafrican.bf/logo_lpk.png",
    image: "https://iafrican.bf/lpk_photo.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Karpala",
    description: "Lycée privé d'excellence à Karpala.",
    descriptionDetaillee: "Cadre d'études discipliné et innovant pour les élèves des séries scientifiques.",
    prixMin: 150000,
    prixMax: 400000,
    prixLabel: "150 000 – 400 000 FCFA/an",
    series: ["Série C", "Série D", "Série A"],
    notationSystem: "National",
    telephone: "+226 25 40 40 40"
  },
  {
    id: "lbg",
    nom: "Lycée Bogodogo",
    sigle: "LBO",
    logo: "https://lefaso.net/logo_lbo.png",
    image: "https://lefaso.net/lbo_campus.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Dassasgo",
    description: "L'un des plus grands lycées de l'Est de la capitale.",
    descriptionDetaillee: "Réputé pour son dynamisme et le sérieux de son corps enseignant.",
    prixMin: 12000,
    prixMax: 20000,
    prixLabel: "12 000 – 20 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National"
  },
  {
    id: "lsc",
    nom: "Lycée Saint-Charles",
    sigle: "LSC",
    logo: "https://stcharles.bf/logo.png",
    image: "https://stcharles.bf/batiment.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Somgandé",
    description: "Établissement confessionnel catholique.",
    descriptionDetaillee: "Discipline de fer et éducation spirituelle pour des résultats records au Bac.",
    prixMin: 200000,
    prixMax: 500000,
    prixLabel: "200 000 – 500 000 FCFA/an",
    series: ["Série A", "Série D", "Série C"],
    notationSystem: "National",
    telephone: "+226 25 35 22 22"
  },
  {
    id: "lwp",
    nom: "Lycée Wend Panga",
    sigle: "LWP",
    logo: "https://wendpanga.bf/logo.png",
    image: "https://wendpanga.bf/lycee.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Secteur 15",
    description: "Établissement privé tourné vers la réussite.",
    descriptionDetaillee: "Un cadre familial et des classes à effectifs réduits.",
    prixMin: 180000,
    prixMax: 450000,
    prixLabel: "180 000 – 450 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National"
  },
  {
    id: "lmp",
    nom: "Lycée Mixte de Pissy",
    sigle: "LMP",
    logo: "https://pissy.bf/logo.png",
    image: "https://pissy.bf/photo.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Pissy",
    description: "Grand lycée public populaire.",
    descriptionDetaillee: "Dessert toute la zone Ouest de Ouagadougou avec des résultats constants.",
    prixMin: 12000,
    prixMax: 22000,
    prixLabel: "12 000 – 22 000 FCFA/an",
    series: ["Série A", "Série D", "Série C"],
    notationSystem: "National"
  },
  {
    id: "lsn",
    nom: "Lycée de Sig-Nonghin",
    sigle: "LSN",
    logo: "https://signonghin.bf/logo.png",
    image: "https://signonghin.bf/campus.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Sig-Nonghin",
    description: "Établissement public de référence au Nord.",
    descriptionDetaillee: "Un corps enseignant expérimenté pour encadrer les élèves du Nord de la ville.",
    prixMin: 11000,
    prixMax: 20000,
    prixLabel: "11 000 – 20 000 FCFA/an",
    series: ["Série A", "Série D"],
    notationSystem: "National"
  }
];

// ── Collèges (10) ─────────────────────────────────────────
const COLLEGES = [
  {
    id: "csj",
    nom: "Collège Saint-Jean de la Salle",
    sigle: "CSJ",
    logo: "https://lefaso.net/IMG/logo/section_college.png",
    image: "https://lefaso.net/IMG/jpg/college_saint_jean.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Baskuy",
    description: "Établissement confessionnel de rigueur.",
    descriptionDetaillee: "Discipline et excellence pour les élèves du premier cycle.",
    prixMin: 150000,
    prixMax: 350000,
    prixLabel: "150 000 – 350 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National",
    telephone: "+226 25 30 61 22"
  },
  {
    id: "cpo",
    nom: "Collège de la Patte d'Oie",
    sigle: "CPO",
    logo: "https://cpo.bf/logo.png",
    image: "https://cpo.bf/campus.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Patte d'Oie",
    description: "Collège public bien structuré.",
    descriptionDetaillee: "Situation privilégiée et encadrement sérieux pour le BEPC.",
    prixMin: 10000,
    prixMax: 15000,
    prixLabel: "10 000 – 15 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "csa",
    nom: "Collège Sainte Anne",
    sigle: "CSA",
    logo: "https://steanne.bf/logo.png",
    image: "https://steanne.bf/photo.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Koulouba",
    description: "Incontournable collège de jeunes filles.",
    descriptionDetaillee: "Formation intégrale et résultats d'exception au BEPC.",
    prixMin: 250000,
    prixMax: 500000,
    prixLabel: "Env. 300 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "cesg",
    nom: "CES de Gounghin",
    sigle: "CESG",
    logo: "https://cesg.bf/logo.png",
    image: "https://cesg.bf/batiment.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Gounghin",
    description: "Collège public dynamique.",
    descriptionDetaillee: "Un pilier du quartier Gounghin pour le premier cycle.",
    prixMin: 9000,
    prixMax: 13000,
    prixLabel: "9 000 – 13 000 FCFA/an",
    series: ["BEPC"],
    notationSystem: "National"
  },
  {
    id: "cmf",
    nom: "Collège Moderne du Faso",
    sigle: "CMF",
    logo: "https://cmf.bf/logo.png",
    image: "https://cmf.bf/photo.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Somgandé",
    description: "Pédagogie active et moderne.",
    descriptionDetaillee: "Établissement privé centré sur l'épanouissement de l'élève.",
    prixMin: 180000,
    prixMax: 400000,
    prixLabel: "180 000 – 400 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "ced",
    nom: "Collège de l'Espérance",
    sigle: "CED",
    logo: "https://esperance.bf/logo.png",
    image: "https://esperance.bf/image.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Tanghin",
    description: "Vers un avenir meilleur.",
    descriptionDetaillee: "Fort soutien scolaire et discipline bienveillante.",
    prixMin: 120000,
    prixMax: 300000,
    prixLabel: "120 000 – 300 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "cesz",
    nom: "CES de Zogona",
    sigle: "CESZ",
    logo: "https://cesz.bf/logo.png",
    image: "https://cesz.bf/photo.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Zogona",
    description: "Pôle d'éducation publique à Zogona.",
    descriptionDetaillee: "Idéalement situé près de l'UJKZ pour inspirer les collégiens.",
    prixMin: 10000,
    prixMax: 14000,
    prixLabel: "10 000 – 14 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "clf",
    nom: "Collège Les Flambeaux",
    sigle: "CLF",
    logo: "https://lesflambeaux.bf/logo.png",
    image: "https://lesflambeaux.bf/photo.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Secteur 22",
    description: "Brillez par le savoir.",
    descriptionDetaillee: "Rigueur religieuse et académique.",
    prixMin: 130000,
    prixMax: 320000,
    prixLabel: "130 000 – 320 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "cpa",
    nom: "Collège Privé de l'Avenir",
    sigle: "CPA",
    logo: "https://cpa.bf/logo.png",
    image: "https://cpa.bf/photo.jpg",
    type: "prive",
    localite: "Ouagadougou",
    quartier: "Wayalghin",
    description: "L'enseignement privé accessible.",
    descriptionDetaillee: "Une chance pour chaque enfant de réussir son premier cycle.",
    prixMin: 100000,
    prixMax: 280000,
    prixLabel: "100 000 – 280 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  },
  {
    id: "cesk",
    nom: "CES de Karpala",
    sigle: "CESK",
    logo: "https://cesk.bf/logo.png",
    image: "https://cesk.bf/photo.jpg",
    type: "public",
    localite: "Ouagadougou",
    quartier: "Karpala",
    description: "Établissement public récent au Sud-Est.",
    descriptionDetaillee: "Désengorge les autres collèges de la zone avec succès.",
    prixMin: 11000,
    prixMax: 16000,
    prixLabel: "11 000 – 16 000 FCFA/an",
    series: ["6ème", "5ème", "4ème", "3ème"],
    notationSystem: "National"
  }
];

// ── Export global ─────────────────────────────────────────
window.CURSUS_DATA = {
  universites: UNIVERSITES,
  lycees: LYCEES,
  colleges: COLLEGES
};
